FlowDemo/main/default/objects/Case/fields/ProductNameGood__c.field-meta.xml
<CustomField>
    <fullName>ProductNameGood__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

FlowDemo/main/default/objects/Drug__c/Drug__c.object-meta.xml
<CustomObject>
    <label>Drug</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlowDemo/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FlowDemo/main/default/objects/Question_Response__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

FlowDemo/main/default/objects/Question_Response__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

FlowDemo/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Questions__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

FlowDemo/main/default/objects/Questions__c/Questions__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Questions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlowDemo/main/default/objects/Questions__c/fields/Drug__c.field-meta.xml
<CustomField>
    <fullName>Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drug</label>
    <referenceTo>Drug__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

FlowDemo/main/default/objects/Questions__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FlowDemo/main/default/classes/drugQuestionnaireController.cls
public with sharing class drugQuestionnaireController
{
    @AuraEnabled
    public static List<Questions__c> getQuestionsFromDrug(String drugId)
    {
        List<Questions__c> qs = [SELECT Id, Name
                                 FROM Questions__c
                                 WHERE Drug__c = :drugId
                                 ORDER BY Order__c];
        return qs;
    }
    
    @AuraEnabled
    public static List<Questions__c> getQuestionsFromCase(String caseId)
    {
        Case c = [SELECT Id, ProductNameGood__c
                  FROM Case
                  WHERE Id = :caseId
                  LIMIT 1];
        
        String drugId = c.ProductNameGood__c;
        
        List<Questions__c> qs = [SELECT Id, Name, Prompt__c
                                 FROM Questions__c
                                 WHERE Drug__c = :drugId
                                 ORDER BY Order__c, Name];

        return qs;
    }
    
    @AuraEnabled
    public static void setQuestionResponses(List<Question_Response__c> questionResponses)
    {
        update questionResponses;
    }
        
    @AuraEnabled
    public static List<Question_Response__c> getQuestionReponsesFromCase(String caseId)
    {
        Case c = [SELECT Id, ProductNameGood__c
                  FROM Case
                  WHERE Id = :caseId
                  LIMIT 1];
        
        String drugId = c.ProductNameGood__c;

        List<Questions__c> reps = [SELECT Id, Name, Prompt__c,
                                   (SELECT Id, Name, Drug__c, Case__c, Response__c, Question__r.Name, Question__r.Prompt__c
                                    FROM Question_Responses__r
                                    WHERE Drug__c = :drugId
                                    AND Case__c = :caseId)
                                   FROM Questions__c
                                   WHERE Drug__c = :drugId
                                   ORDER BY Order__c, Name];
        
        List<Question_Response__c> qrs = new List<Question_Response__c>();
        
        for (Questions__c q : reps)
        {
            Integer s = q.Question_Responses__r.size();
            if (s < 1)
            {
                Question_Response__c qr;
                qr = new Question_Response__c();
                qr.Drug__c = drugId;
                qr.Case__c = caseId;
                qr.Question__c = q.Id;
                qr.Response__c = '';
                qrs.add(qr);
            }
        }
        
        if (qrs.size() > 0)
        {
        	insert qrs;
        }
        
        qrs = [SELECT Id, Name, Drug__c, Case__c, Response__c, Question__r.Name, Question__r.Prompt__c
               FROM Question_Response__c
               WHERE Drug__c = :drugId
               AND Case__c = :caseId];
        
        return qrs;
    }
    
}